### ISSUE TITLE
Nothing is showing below 767px

### ISSUE THREAD

**Issue by jitendravyas** [openam/bootstrap-responsive-tabs#12]
I'm using this plugin and it's working. but nothing is visible below 767px. I'm using Bootstrap 3. and below is the part which keep the panel hidden

.visible-sm, tr.visible-sm, th.visible-sm, td.visible-sm {
display: none !important;
}
toolkitmedia="all"
.visible-xs, tr.visible-xs, th.visible-xs, td.visible-xs {
display: none !important;
}

**Comment by jitendravyas** [comment]
With which version of Bootstrap this plugin is not compatible? In my project Bootstrap version is 3.1

**Comment by openam** [comment]
Looks like there is a problem with version 3.1.0, but 3.1.1 works fine ```//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css```
