### ISSUE TITLE
Embedded Twitter Feed Disappears on resize

### ISSUE THREAD

**Issue by janecky** [openam/bootstrap-responsive-tabs#15]
It appears that embedding a twitter feed inside the tab content area breaks on resize. Any ideas on a resolution?
Here is a jsfiddle:
http://jsfiddle.net/1c367qth/1/
In this fiddle, the twitter feed doesn't show up at all within the accordion. In my local testing it appears only on page load. Resizing breaks it.

**Comment by openam** [comment]
Should have been fixed in #30.
