### ISSUE TITLE
Error resizing -  when tab contains a panel with body

### ISSUE THREAD

**Issue by nikitul** [openam/bootstrap-responsive-tabs#17]
If inside of div with class="tab-content" we have a panel with his body (class="panel-body"), when we try to resize, it happens 2 things:
1. This error is coming up:
TypeError: $(...).attr(...) is undefined
var destinationId = $( tabContent ).attr( 'id' ).replace ( /^/, '#collapse-' );
2. It ruins the content of the panel

Please check resizing on fiddle:http://jsfiddle.net/r0k8244t/1/

**Comment by openam** [comment]
It looks like this would be fixed with #39.
