### ISSUE TITLE
Browser window resize problem

### ISSUE THREAD

**Issue by darnook** [openam/bootstrap-responsive-tabs#19]
Hi. 
I have noticed that bug also in Your demo site
When i resize browser window width to minimum (to check responsivenes) the responsive tabs works perfectly but when i resize to full width the content in this tabs are missing. Any ideas? Thanks in advance!

**Comment by papakay** [comment]
Thanks nkdweb, The information provided on the reference link works fine.

**Comment by openam** [comment]
Should have been fixed in #30.
