### ISSUE TITLE
add a span-tag

### ISSUE THREAD

**Issue by wini2** [openam/bootstrap-responsive-tabs#22]
hi,

i'd like to have the whole panel-tiltle clickable. therefor i added the css mentioned in https://github.com/openam/bootstrap-responsive-tabs/issues/5.

is there a way to add a span-tag behind the h4-tag in order to  show up a glyphicon - something like

< span class="pull-right collapse-handle glyphicon glyphicon-chevron-down" >< /span > and 
< span class="pull-right collapse-handle glyphicon glyphicon-chevron-up" >< /span >

depending on the accordion-state?

thank you for your help

**Comment by openam** [comment]
This would be possible if/when #4 gets implemented.
