### ISSUE TITLE
Change breakpoint to 1024 for tabs

### ISSUE THREAD

**Issue by Sushil-Dhiver** [openam/bootstrap-responsive-tabs#34]
Hi. 
is there any way to change the breakpoint? right now the accordion is visible when the width is 992px or less. can this be changed? I am having around 10 tabs in my page and when I try to view it in an Ipad in landscape mode, it doesn't show me the accordion. is there a way to set it somewhere?

**Comment by openam** [comment]
No, the breakpoint correspond to the breakpoints defined in the [bootstrap grid layout](http://getbootstrap.com/css/#grid-options).  You can change which breakpoint it uses by changing what it's started with, e.g. `fakewaffle.responsiveTabs(['xs', 'sm']);` vs `fakewaffle.responsiveTabs(['xs', 'sm', 'md']);`,  which would make accordions for anything < 1200px.

**Comment by Sushil-Dhiver** [comment]
oh. great.
thank you very much :+1:
