### ISSUE TITLE
Compatible issue? "tab-content" do not recover after resizing to full screen on desktop

### ISSUE THREAD

**Issue by TsuiJie** [openam/bootstrap-responsive-tabs#36]
I'm using Bootstrap version 3.3.2

![image](https://cloud.githubusercontent.com/assets/5970965/7875150/daafa4e4-05eb-11e5-896e-1cf6719874a9.png)

This div should be filled with content while resizing back to normal size but it did not.

**Comment by sic0211** [comment]
Add an id to nav-tabs
<ul class="nav nav-tabs responsive" id="navTabs">

So the script remembers the id to switch back to tabs from accordion after resize

**Comment by sic0211** [comment]
It's weird I can't use tags

**Comment by sic0211** [comment]
It's weird I can't use tags
ul class="nav nav-tabs responsive" id="navTabs"

**Comment by TsuiJie** [comment]
Thanks, I've already solved this problem, scripts are compatible with the latest Bootstrap version.
