### ISSUE TITLE
Not working on Popup Modal

### ISSUE THREAD

**Issue by wedangsusu** [openam/bootstrap-responsive-tabs#38]
Hi

I have issue when i am use popup, you can see this screenshot
![screenshot_2](https://cloud.githubusercontent.com/assets/12873167/8856550/0f567712-319e-11e5-9b12-4fe57e9884f1.png)

Thanks

**Comment by mav2287** [comment]
Had this same issue. The problem may be that you have in your document ready function. Call it again when the dialog is shown. The dialog is dynamic so the code isn't applied to. By applying it when the dialog is shown you should solve the issue.

onshown: function(dialogRef){
		fakewaffle.responsiveTabs(['xs', 'sm']);
	}

**Comment by openam** [comment]
Closing as the previous comment sounds like the proper solution.
