### ISSUE TITLE
Scroll to bottom on first click

### ISSUE THREAD

**Issue by jpswade** [openam/bootstrap-responsive-tabs#41]
1. In mobile view, open http://openam.github.io/bootstrap-responsive-tabs/
2. Scroll down below "How to" section and click on the "Key Features" tab.

You'll be taken to the bottom of the page.

**Comment by openam** [comment]
This is due to the fact that the `How To` section had so much more content than the `Key Features` section. This is the same thing that would happen if you created a vanilla Bootstrap `collapse` with that same content.
