### ISSUE TITLE
Panel content disappear

### ISSUE THREAD

**Issue by SojeSkormdark** [openam/bootstrap-responsive-tabs#42]
Hi,

I'm using your responsive Tabs and having some trouble. In fact, i test the functionnaly by resize my browser and everything work great when i go from lg screen to xs or sm screen but when i come back, the content of my tabs on lg disappear..
There is no more things inside..

Do you know how I can fix it or if something already happen?

Thanks!

**Comment by mav2287** [comment]
I had this same issue. It was because I didn't assign an id to my <UL  class="nav nav-tabs responsive"> and <div class="tab-content responsive">. Try adding an id to these elements <ul id="TabsID1" class="nav nav-tabs responsive"> and <div id="TabContentID1" class="tab-content responsive">.

**Comment by openam** [comment]
This should be fixed with, 78384a715fc5aef0babcdbd35d488b75b4abb681. Which was PR #30.
