### ISSUE TITLE
Leave each tab open until clicked again

### ISSUE THREAD

**Issue by jpatrickm** [openam/bootstrap-responsive-tabs#44]
Is it possible to leave each tab open when another one is clicked so that they just individually toggle and aren't connected to each other? The problem is that when one tab is open and another tab is clicked, the collapsing tab above causes the page content to jump significantly so the user doesn't know where they were on the page.

**Comment by jpatrickm** [comment]
Or alternatively some kind of jump or auto-scroll to the top of the active tab that I've seen with the Bootstrap accordion function.

**Comment by foloed** [comment]
Odd, we both needed this at around the same time.
I have submitted a pull request with the code requested.
