### ISSUE TITLE
Open tabs on collapsed container

### ISSUE THREAD

**Issue by BredeBS** [openam/bootstrap-responsive-tabs#49]
Hi
I have a container who start closed when the pages load. When I expand the container, the tabs doesn't works
Steps:
1.- A Container (div) closed (by jquery on document ready)
2.- 4 tabs inside that container
3.- click a button to open the Container
4.- the tabs doesn't answer
5.- when I resize the page the tabs shows automatically (and works)

I try to call the function fakewaffle.responsiveTabs(['xs', 'sm']) in the 3rd step, but that duplicate the tabs.

Also, there is a way to call the function like $("#mytabs").responsiveTabs(['xs', 'sm']) [or a way to destroy it?]

Thanks!

**Comment by openam** [comment]
Can you provide a jsfiddle or something? I'm not sure what you're doing.

**Comment by openam** [comment]
Closing do to no response
