### ISSUE TITLE
Issue when using Bootstrap fade class

### ISSUE THREAD

**Issue by gellmaster** [openam/bootstrap-responsive-tabs#9]
Cool solution to a common problem. Thanks for putting it out here.

I ran into an issue utilizing the fade class with tabs that I thought I’d report.

Using your example code I can reproduce the issue.
- Add the "fade" class to divs with tab-pane. 
- On initial load of the page when in panel mode, click “Key Features” or “Source” panel. 

“How To” will stay open in addition to the other panel opening.  It works correctly with subsequent collapses on any panel. I've tested with Bootstrap 3.2.0 and the problem still exists.

Removing fade from my tab-panes everything works as expected. I’m not exactly sure of the root cause, something to do with the transition and timing probably, but it may be worth documenting unless a solution is found.

Here is a jsfiddle that demos the issue with the same setup as your example page.
http://jsfiddle.net/r429t/

**Comment by openam** [comment]
The unrelated note should have been addressed with #39.
